# Generated by Django 3.2.25 on 2024-08-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieinfo',
            name='title',
            field=models.CharField(max_length=25),
        ),
    ]
