# Generated by Django 3.2.25 on 2024-08-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_alter_movieinfo_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieinfo',
            name='title',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
